# -*- coding: utf-8 -*-
"""FaceRecognition_DeepLearning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16cu5s5CxLB-Grl9vfjPC7pSPrt5_Tg9L
"""

#Name:Glory Joe-Ibekwe
#Student id: w2144448

!pip install tensorflow-gpu

!pip install face_recognition

!pip install pillow

!pip install dlib==19.18

from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

import PIL.Image
import PIL.ImageDraw
import face_recognition

#load jpeg file into numpy array
image = face_recognition.load_image_file("skye.jpg")

#FIND ALL THE FACES IN THE IMAGE
face_locations = face_recognition.face_locations(image)
number_of_faces = len(face_locations)
print("I found {} face(s) in the photograph".format(number_of_faces))

#Load the image into the python image library object so that we can draw on to of it and display it
pil_image = PIL.Image.fromarray(image)

for face_location in face_locations:
  #print the location of each face in this image. each face is a list of co-ordinates in top, left, right bottom order
  top, right, bottom, left = face_location
  print("A face is located at pixel location Top: {}, Left: {}, Bottom: {}, Right: {}".format(top, left, bottom, right))
  #lets draw a line/box on/around the face
  draw = PIL.ImageDraw.Draw(pil_image)
  draw.rectangle([left, top, right, bottom], outline="red")

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.image as mpimg
from matplotlib.pyplot import imshow
# %matplotlib inline
from IPython.display import Image

imshow(pil_image)

#find all facial features in all the faces in the image
face_landmark_list = face_recognition.face_landmarks(image)
#loop over each face
for face_landmarks in face_landmark_list:
  #loop over each facial feature (eye, nose, mouth,lips, etc)
  for name, list_of_points in face_landmarks.items():
    #print the location of ech feature in the image
    print("The {} in this face has the folloing points: {}".format(name, list_of_points))

    #let's trace out each facial feature in the image with a line!
    draw.line(list_of_points, fill="red", width=2)

imshow(pil_image)

#Generate the Face Encoding
face_encodes = face_recognition.face_encodings(image)
if len(face_encodes) == 0:
  #no faces found in the image.
  print('No faces were found')
else:
  #grab the first face encoding
  first_face_encodes = face_encodes[0]
  #print the result
  print(first_face_encodes)

from google.colab import drive
drive.mount('/content/drive')

"""# New Section"""